### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by ghost** [zhuchangyi/Gemini2tg#1]
At the end of the script we have an error and the robot does not work here is the error

" Python script downloaded successfully.
Gemini2tg is running in the background.
root@BoomieAIBOT:~# nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
nohup: failed to run command 'python3.9': No such file or directory "

**Comment by zhuchangyi** [comment]
Hello coymine,

The message "nohup: appending output to 'nohup.out'" indicates that the script is already running in the background, so you can ignore the "python3.9 wrong" message. I suggest you try sending a /start command to your bot to see if it responds. If there is no response, it could be due to the incorrect Python version or missing packages.
1. Which operating system you are using? 
2. Please navigate to the gemini folder, and check the Python version and the installed packages in the gemini2tg environment:
 ``` 
cd gemini
 ``` 
Then activate the gemini2tg environment using the following command:
 ``` 
source gemini2tg/bin/activate
python -V # Check if your Python version is 3.9 or higher
pip list  # Check if all necessary packages are installed
 ``` 
3. Check the output of nohup to see if there are any errors:
 ``` 
cat nohup.out # This may help you identify the main issue; you can paste a few lines of the output here
``` 
Looking forward to your response.
